---

version: '3.8'

services:
  app:
    image: node:14-slim
    working_dir: /var/local/app/myproject/
    #command: npm start
    volumes:
      - type: bind
        #source: ${PWD}/myproject/
        source: ${PWD}/myproject2/
        target: /var/local/app/myproject/
    ports:
      - 1234:1234
  nginx:
    image: nginx:stable
    volumes:
      - type: bind
        source: ${PWD}/by-jquery/
        target: /usr/share/nginx/html/
    ports:
      - 80:80
  react:
    image: node:14-slim
    working_dir: /var/local/app/by-react/
    #command: yarn start
    volumes:
      - type: bind
        source: ${PWD}/by-react/
        target: /var/local/app/by-react/
    ports:
      - 3000:3000
